; -----------------------------------------------------------------------
; Template source file generated by piklab
    #include <p16f628a.inc>

; -----------------------------------------------------------------------
; Configuration bits: adapt to your setup and needs
    __CONFIG _WDT_OFF & _PWRTE_OFF & _HS_OSC & _MCLRE_ON & _BODEN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF

; -----------------------------------------------------------------------


; -----------------------------------------------------------------------
; reset vector
STARTUP CODE 0x000
  nop

start

    MOVLW 0x07
    MOVWF CMCON

    BANKSEL TRISA
    MOVLW 0xFF 
    MOVWF TRISA
    MOVLW 0x01
    MOVWF PORTB
    BANKSEL PORTA
   
    CLRF PORTB
 
    BSF PORTB,0
    
    BANKSEL TRISA
    BCF PORTB,0
    BANKSEL PORTA		

    BTFSC PORTB,0
    BSF PORTB,1


    ; << insert main code >>
    goto    $              ; loop forever

END
