; -----------------------------------------------------------------------
; Template source file generated by piklab
    #include <p16f628a.inc>

; -----------------------------------------------------------------------
; Configuration bits: adapt to your setup and needs
    __CONFIG _WDT_OFF & _PWRTE_OFF & _RC_OSC_CLKOUT & _MCLRE_OFF & _BOREN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF

; -----------------------------------------------------------------------


	org 0x00
	nop
	movlw 0x07 
	movwf CMCON
	BANKSEL TRISA 
	CLRF TRISA
	CLRF TRISB
	BANKSEL PORTA
start
	nop	
	nop
   	MOVLW PORTA
	MOVWF FSR
	CLRF INDF
	MOVLW 0xFF
	XORWF INDF,F
	INCF FSR,F
	MOVLW B'00001111'
	MOVWF INDF
	MOVLW 0xFF
	XORWF INDF,F
	goto    start  ; loop forever

END
