/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f628a.h>

/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word at 0x2007 CONFIG = _WDT_ON & _PWRTE_OFF & _RC_OSC_CLKOUT & _MCLRE_ON & _BOREN_ON & _LVP_ON & _DATA_CP_OFF & _CP_OFF;

void isr() interrupt 0 {                                                                                                  /* interrupt service routine */
    /* << insert interrupt code >> */
}

void main() {
    /* << insert code >> */
}
