/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f628a.h>

#include "nop.h"

/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word at 0x2007 CONFIG = _WDT_OFF & _PWRTE_OFF & _INTOSC_OSC_NOCLKOUT & _MCLRE_ON & _BOREN_OFF & _LVP_OFF & _DATA_CP_OFF & _CP_OFF;


unsigned char cont1=1;
unsigned char cont2=254;
unsigned int i;

void main() 
{
    /* << insert code >> */
   TRISA=0xFF;
   TRISB=0;

   while(1)
   {
     PORTB=cont1;
     cont1++;
     
     for(i=0; i < 5120; i++)
     {
       nop(); 
     } 	
  }
}
