/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic18f452.h>

#include <float.h>

/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
code char at __CONFIG1H CONFIG1H = _OSC_HS_1H & _OSCS_OFF_1H;
code char at __CONFIG2L CONFIG2L = _PUT_OFF_2L & _BODEN_OFF_2L & _BODENV_2_0V_2L;
code char at __CONFIG2H CONFIG2H = _WDT_OFF_2H & _WDTPS_1_128_2H;
code char at __CONFIG3H CONFIG3H = _CCP2MUX_RC1_3H;
code char at __CONFIG4L CONFIG4L = _STVR_ON_4L & _LVP_OFF_4L & _BACKBUG_OFF_4L;
code char at __CONFIG5L CONFIG5L = _CP_0_OFF_5L & _CP_1_OFF_5L & _CP_2_OFF_5L & _CP_3_OFF_5L;
code char at __CONFIG5H CONFIG5H = _CPB_OFF_5H & _CPD_OFF_5H;
code char at __CONFIG6L CONFIG6L = _WRT_0_OFF_6L & _WRT_1_OFF_6L & _WRT_2_OFF_6L & _WRT_3_OFF_6L;
code char at __CONFIG6H CONFIG6H = _WRTC_OFF_6H & _WRTB_OFF_6H & _WRTD_OFF_6H;
code char at __CONFIG7L CONFIG7L = _EBTR_0_OFF_7L & _EBTR_1_OFF_7L & _EBTR_2_OFF_7L & _EBTR_3_OFF_7L;
code char at __CONFIG7H CONFIG7H = _EBTRB_OFF_7H;

#define ICLK PORTCbits.RC3
#define IDAT PORTCbits.RC4
#define TIDAT TRISCbits.TRISC4

void delay(void)
{
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
}

void i2c_init(void)
{
  TIDAT=0;
  ICLK=1;
  IDAT=1;
}

void i2c_start(void)
{
  ICLK=1;
  IDAT=1;
  delay();
  IDAT=0;
  delay();
}

void i2c_stop(void)
{
  ICLK=1;
  IDAT=0;
  delay();
  IDAT=1;
  delay();
}

void i2c_wb(unsigned char val)
{
  unsigned char i;
  ICLK=0;
  for(i=0;i<8;i++)		
  {
    IDAT=((val>>(7-i))& 0x01);
    ICLK=1;
    delay();
    ICLK=0;
  }	
  IDAT=1;
  delay();
  ICLK=1;
  delay();
  ICLK=0;
}

unsigned char i2c_rb(void)
{
  unsigned char i;
  unsigned char ret=0;

  ICLK=0;
  TIDAT=1;
  IDAT=1;
  for(i=0;i<8;i++)
  {
    ICLK=1;
    delay();
    ret|=(IDAT<<(7-i));
    ICLK=0;
  }
  TIDAT=0;
  IDAT=0;
  delay();
  ICLK=1;
  delay();
  ICLK=0;

  return ret;
}



void main(){
  volatile  char i;
  volatile unsigned char val;

  ADCON1=0x06;
  TRISA=0xFF;
  TRISB=0x00;
  TRISC=0x11;
  TRISD=0x00;
  TRISE=0xFC;



  TIDAT=0;
  ICLK=1;
  IDAT=1;

  ICLK=1;
  IDAT=1;
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
  IDAT=0;
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 


  val=0x5A;

  ICLK=0;

 
  for(i=7;i >=0 ;i--)		
  {
    IDAT=((val>>(i))& 0x01); 
    ICLK=1;
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
  _asm  NOP _endasm; 
    ICLK=0;
  }

  IDAT=1;
  delay();
  ICLK=1;
  delay();
  ICLK=0;


/*
  i2c_init();

  i2c_start();	
  i2c_wb(0xA0);

  i2c_wb(0x00);
  i2c_wb(0x01);

  i2c_start();
  i2c_wb(0xA1);
  PORTB=i2c_rb();
  i2c_stop();
*/
  while(1);


}

