; -----------------------------------------------------------------------
; Template source file generated by piklab
    #include <p16f628a.inc>

; -----------------------------------------------------------------------
; Configuration bits: adapt to your setup and needs
    __CONFIG _WDT_ON & _PWRTE_OFF & _RC_OSC_CLKOUT & _MCLRE_ON & _BODEN_ON & _LVP_ON & _DATA_CP_OFF & _CP_OFF

; -----------------------------------------------------------------------
; Variables declaration
INT_VAR UDATA_SHR
w_saved      RES 1 ; variable used for context saving
status_saved RES 1 ; variable used for context saving
pclath_saved RES 1 ; variable used for context saving

var1         RES 1 ; example variable

; -----------------------------------------------------------------------
; reset vector
STARTUP CODE 0x000
    nop                    ; needed for ICD2 debugging
    goto    start          ; go to start of main code

; interrupt vector
INT_VECTOR CODE 0x004
    goto    interrupt      ; go to start of interrupt code

; relocatable code
PROG CODE
interrupt
    BCF STATUS,RP1
    BCF STATUS,RP0
    movlw 0xff	
    movwf PORTB
    BCF PIR1,TMR2IF
    retfie

start
    BSF PIR1,TMR2IF
    BSF INTCON,GIE
    BSF INTCON,PEIE
    banksel PIE1
    BSF PIE1,TMR2IE
 
loop: 
     nop
     nop 
     goto loop    

                      ; loop forever

END
